debug: true
spring:
  devtools:
    livereload:
      enabled: true

security:
  user:
    password: initial
#eureka:
#  client:
#      region: default
#      registryFetchIntervalSeconds: 5
#      serviceUrl:
#        defaultZone: http://user:Hello1234@localhost:8761/eureka/

#spring.zipkin.base-url=${vcap.services.zipkin-service.credentials.uri}
#spring.rabbitmq.host=${vcap.services.reservations-rabbitmq.credentials.uri}
