debug: true
info:
  id: ${spring.application.name}
server:
  port: ${PORT:0}

eureka:
  client:
      region: default
      registryFetchIntervalSeconds: 5
      serviceUrl:
        defaultZone: ${vcap.services.discovery-service.credentials.uri:http://user:Hello1234@localhost:8761}/eureka/

spring:
  cloud:
    stream:
      binder:
        rabbit:
          default:
            default-delivery-mode: persistent
            acknowledge-mode: manual
            durable-subscription: true
            transacted: true
            default-requeue-rejected: true
            auto-bind-dlq: true
            republish-to-dlq: true
#spring.sleuth.sampler.percentage=1.0
#logging.level.org.springframework.security=DEBUG
#logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex

#spring.sleuth.log.json.enabled=true

#spring.zipkin.host=${DOCKER_IP}

#spring.cloud.consul.host=${DOCKER_IP}
#spring.cloud.consul.discovery.hostname=${DOCKER_HOST_IP:cna}

#logging:
#  level:
#    com.netflix.eureka: OFF
#    com.netflix.discovery: OFF


#spring.redis.host=${DOCKER_IP}

#spring.zipkin.base-url=http://${DOCKER_IP}:9411
#spring.zipkin.base-url=http://127.0.0.1:9411





#endpoints.shutdown.enabled=true

#spring.jpa.generate-ddl=true


#eureka.instance.hostname=${vcap.application.uris[0]:localhost}
#eureka.instance.nonSecurePort=80


#endpoints.shutdown.enabled=true

#spring.jpa.generate-ddl=true
