server:
  port: ${PORT:8003}

iot:
  platform:
    enable:
      thing-repository: true
      event-repository: false
      authorization-repository: true

spring:
  cloud:
    stream:
      bindings:
        movement:
          group: timeseries
          destination: cta.edge.ingestion.movements
          content-type: application/json
