server:
  port: ${PORT:8004}

spring:
  cloud:
    stream:
      bindings:
        email:
          group: email
          destination: cta.core.notification
          content-type: application/json

email:
  from: sap.riesenrad@gmail.com
  imaps-host: imap.gmail.com
  smtp-auth: true
  smtp-host: smtp.gmail.com
  smtp-port: 587
  smtp-starttls-enable: true
  store-protocol: imaps
  transport-protocol: smtp
