server:
  port: ${PORT:8004}

spring:
  cloud:
    stream:
      bindings:
        email:
          group: email
          destination: cta.core.notification
          content-type: application/json

email: 
  mail:
    from: sap.riesenrad@gmail.com
    imaps:
      host: imap.gmail.com
    smtp:
      auth: true
      host: smtp.gmail.com
      port: 587
    store:
      protocol: imaps
    transport:
      protocol: smtp
