server:
  port: ${PORT:8005}

security:
  user:
    password: initial

spring:
  cloud:
    stream:
      bindings:
        movement:
          destination: cta.ingestion.pipe
          group: planogram-ingestion-movement
          content-type: application/json
        planogram:
          destination: cta.ingestion.pipe
          group: planogram-ingestion-planogram-update
          content-type: application/json
