server:
  port: ${PORT:8002}

security:
  user:
    password: initial
    
spring:
  cloud:
    stream:
      bindings:
        movement:
          destination: cta.edge.ingestion.movements
          content-type: application/json
          producer:
            requiredGroups: event,timeseries
        planogram:
          destination: cta.edge.ingestion.planogram
          content-type: application/json
          producer:
            requiredGroups: planogram
