server:
  port: ${PORT:8003}
  
security:
  user:
    password: initial

spring:
  cloud:
    stream:
      bindings:
        movement:
          destination: cta.ingestion.pipe
          content-type: application/json
        planogram:
          destination: cta.ingestion.pipe
          content-type: application/json
        event:
         destination: cta.ingestion.pipe
         content-type: application/json